services:
  postgres17:
    image: postgres:17
    pull_policy: 'always'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shadow
      POSTGRES_DB: kerp_shipping
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
