"""Create shipments table.

Revision ID: 99fd0eb0a6a8
Revises: 8213cad99c06
Create Date: 2024-04-25 13:53:43.397970+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "99fd0eb0a6a8"
down_revision = "8213cad99c06"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipments",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
            comment="Unique ID for this shipment",
        ),
        sa.Column("carton_number", sa.String(), nullable=False, comment="K-ERP carton number"),
        sa.Column("tracking_number", sa.String(), nullable=True, comment="FedEx tracking number"),
        sa.Column("status", sa.String(), nullable=False, comment="Shipment status"),
        sa.Column(
            "fedex_create_label_request",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="FedEx label creation request data",
        ),
        sa.Column(
            "fedex_create_label_response",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="FedEx label creation response data",
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The date and time the object was created",
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The date and time the object was last updated",
        ),
        sa.Column(
            "deleted",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="The date and time the object was deleted (NULL if not deleted)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipments")
    # ### end Alembic commands ###
