"""Add settings table.

Revision ID: e5ba6d3211a5
Revises: 99fd0eb0a6a8
Create Date: 2024-12-30 16:48:53.937689+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e5ba6d3211a5"
down_revision = "99fd0eb0a6a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
            comment="Unique ID for this setting",
        ),
        sa.Column("ship_from_company", sa.String(), nullable=False, comment="Ship from company name"),
        sa.Column("ship_from_name", sa.String(), nullable=False, comment="Ship from contact name"),
        sa.Column("ship_from_phone", sa.String(), nullable=False, comment="Ship from contact phone"),
        sa.Column("ship_from_address_1", sa.String(), nullable=False, comment="Ship from address line 1"),
        sa.Column("ship_from_address_2", sa.String(), nullable=False, comment="Ship from address line 2"),
        sa.Column("ship_from_city", sa.String(), nullable=False, comment="Ship from city"),
        sa.Column("ship_from_state", sa.String(), nullable=False, comment="Ship from state"),
        sa.Column("ship_from_postal_code", sa.String(), nullable=False, comment="Ship from postal code"),
        sa.Column("ship_from_country_code", sa.String(), nullable=False, comment="Ship from country code"),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The date and time the object was created",
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The date and time the object was last updated",
        ),
        sa.Column(
            "deleted",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="The date and time the object was deleted (NULL if not deleted)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    # ### end Alembic commands ###
