"""Add label size to settings.

Revision ID: 1447a72de5c3
Revises: e5ba6d3211a5
Create Date: 2025-01-29 02:08:02.211724+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1447a72de5c3"
down_revision = "e5ba6d3211a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "fedex_label_size",
            sa.Enum("STOCK_4X6", "STOCK_4X675_LEADING_DOC_TAB", "STOCK_4X675_TRAILING_DOC_TAB", native_enum=False),
            nullable=True,
            comment="FedEx label size",
        ),
    )
    op.execute("UPDATE settings SET fedex_label_size = 'STOCK_4X6'")
    op.alter_column("settings", "fedex_label_size", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "fedex_label_size")
    # ### end Alembic commands ###
