"""Store K-ERP tracking upload response.

Revision ID: d4700b5b6c18
Revises: 1447a72de5c3
Create Date: 2025-07-02 00:28:31.421921+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d4700b5b6c18"
down_revision = "1447a72de5c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shipments",
        sa.Column("kerp_tracking_upload_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shipments", "kerp_tracking_upload_response")
    # ### end Alembic commands ###
